Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,20 +19,18 @@ jobs:
       id:  xcodetest
       run: 
         xcodebuild -project UnitSample.xcodeproj -scheme "UnitSample" -testPlan "UnitSample1"  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro'  -configuration Debug  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -resultBundlePath "testReports/TestResult.xcresult" test > mycustomfile;
-        if grep -q "** TEST FAILED **" mycustomfile
-        then
-        echo "Test has failed so exiting..."
-        exit 1
+        
+        if grep -q "** TEST FAILED **" mycustomfile; then
+        echo "Test has failed so exiting...";
+        exit 1;
         else
-        cat mycustomfile | xcpretty --test --color --report html --output TestReports/report.html
+        cat mycustomfile | xcpretty --test --color --report html --output TestReports/report.html;
         fi
-        rm mycustomfile
-        echo "::set-output name=estatus::$PIPESTATUS"
+        
+        rm mycustomfile;
+      
     - name: Test Reports
       uses: actions/upload-artifact@v1
       with:
           name: testReports
           path: TestReports
-    - name: Check Tests Passed
-      if: steps.xcodetest.outputs.estatus != 0
-      run: exit 1
